# Generated by Django 3.0.4 on 2020-04-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='auther',
            new_name='author',
        ),
    ]
