# Generated by Django 3.0.4 on 2020-04-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowen', '0002_auto_20200417_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_time']},
        ),
    ]
