# Generated by Django 3.0.8 on 2020-07-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowen', '0007_auto_20200730_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
